// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated />

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.DynamicValues;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Players;
    using Eco.Gameplay.Skills;
    using Eco.Shared.Utils;
    using Eco.World;
    using Eco.World.Blocks;
    using Gameplay.Systems.TextLinks;
    using Eco.Shared.Localization;

    /// <summary>Auto-generated class. Don't modify it! All your changes will be wiped with next update! Use Mods* partial methods instead for customization.</summary>
    [RequiresSkill(typeof(RanchingSkill), 2)]
    public partial class MilkBisonRecipe :
        RecipeFamily
    {
        public MilkBisonRecipe()
        {
            this.Recipes = new List<Recipe>
            {
                new Recipe(
                    "MilkBison",
                    Localizer.DoStr("Milk Bison"),
                    new IngredientElement[]
                    {
               new IngredientElement(typeof(DomesticatedBisonItem), 1, true),
                    },
                    new CraftingElement[]
                    {
               new CraftingElement<MilkItem>(2),
               new CraftingElement<DomesticatedBisonItem>(1),

                    })
            };
            this.ExperienceOnCraft = 5;
            this.LaborInCalories = CreateLaborInCaloriesValue(40, typeof(RanchingSkill));
            this.CraftMinutes = CreateCraftTimeValue(typeof(MilkBisonRecipe), 2.5f, typeof(RanchingSkill));
            this.ModsPreInitialize();
            this.Initialize(Localizer.DoStr("Milk Bison"), typeof(MilkBisonRecipe));
            this.ModsPostInitialize();
            CraftingComponent.AddRecipe(typeof(NewAnimalFeederObject), this);
        }

        /// <summary>Hook for mods to customize RecipeFamily before initialization. You can change recipes, xp, labor, time here.</summary>
        partial void ModsPreInitialize();
        /// <summary>Hook for mods to customize RecipeFamily after initialization, but before registration. You can change skill requirements here.</summary>
        partial void ModsPostInitialize();
    }
}
